switched to poetry package management
AntonOsika/gpt-engineer pull request #1
Opened 2023-06-11 01:59 UTC by JacobFV

Thank thank you thank you Anton. You won. My dream of building [ComputaCode](https://computaco.ai/computa-code) is probabbly over. lol. It's okay. I'm happy for everyone else.

For reproducibility purposes, I recommend using poetry since it records package versions. Please see my fork.

2023-06-11 02:40 UTC, JacobFV commented
Had to make some more changes to get poetry to work from the CLI. But now you *should* have entry points that pipx recognizes.

2023-06-11 02:41 UTC, JacobFV commented
Refactoring the path management

2023-06-11 02:55 UTC, JacobFV commented
Ready to merge

2023-06-11 16:26 UTC, AntonOsika commented on gpt_engineer/__main__.py
> +    app_dir = pathlib.Path(__file__).parent.parent  # typer.get_app_dir(APP_NAME))
```suggestion
    app_dir = pathlib.Path(__file__).parent.parent
```

2023-06-11 16:27 UTC, AntonOsika commented on gpt_engineer/__main__.py
> +APP_NAME = "gpt-engineer"
```suggestion
APP_NAME = "gpt-engineer"
```

2023-06-11 16:35 UTC, AntonOsika commented
Thanks so much for the PR!

There are some conflicts now, and I can't fix them before merge.

If you do it I'd be happy to merge.

Also: do you want to delete __pycache__ files and my-new-project directory? ❤️

2023-06-11 16:35 UTC, AntonOsika requested changes

2023-06-11 16:35 UTC, AntonOsika commented on gpt_engineer/__main__.py
> +APP_NAME = "gpt-engineer"
Do we need this:)

2023-06-11 17:06 UTC, JacobFV commented
> Thanks so much for the PR!
> 
> 
> 
> There are some conflicts now, and I can't fix them before merge.
> 
> 
> 
> If you do it I'd be happy to merge.
> 
> 
> 
> Also: do you want to delete __pycache__ files and my-new-project directory? ❤️ 

Thanks. I see. 

Away from home rn but will commit in about an hour

Yes

2023-06-11 20:27 UTC, JacobFV reviewed
done?

2023-06-11 20:28 UTC, JacobFV commented on gpt_engineer/__main__.py
> +APP_NAME = "gpt-engineer"
No

2023-06-11 20:30 UTC, JacobFV commented
I think this is ready to merge, but Github won't let me. I'm able to merge on my machine tho:

![Screenshot from 2023-06-11 15-30-03](https://github.com/AntonOsika/gpt-engineer/assets/40343913/2e124a37-39f5-49b3-baca-cb2ef0a1aedc)
![Screenshot from 2023-06-11 15-29-23](https://github.com/AntonOsika/gpt-engineer/assets/40343913/fdd9bde7-a0e3-49b6-a475-ebf708888ecb)

2023-06-12 06:35 UTC, AntonOsika commented
Thanks @JacobFV!

To resolve the conflicts you need to do a pull on the main branch of the repo.

I.e. something like:

`git remote add upstream https://github.com/AntonOsika/gpt-engineer`

`git pull upstream`

And then resolve conflicts (I use pycharm to resolve but up to you ofc)

2023-06-14 23:09 UTC, justinhartman commented on gpt_engineer/__pycache__/__main__.cpython-310.pyc
You probably want to remove all your `pyc` files and `__pycache__` folder since you're excluding them in the .gitignore file?

2023-06-14 23:11 UTC, offiub commented
Okay sir . You have some issues to rectify

On Thu, Jun 15, 2023 at 12:09 AM Justin Hartman ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> On gpt_engineer/__pycache__/__main__.cpython-310.pyc
> <https://github.com/AntonOsika/gpt-engineer/pull/1#discussion_r1230257190>
> :
>
> You probably want to remove all your pyc files and __pycache__ folder
> since you're excluding them in the .gitignore file?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/AntonOsika/gpt-engineer/pull/1#pullrequestreview-1480431927>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BASR7VW2BDQYFVSJZDE7N6DXLJACXANCNFSM6AAAAAAZCATISM>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2023-06-14 23:16 UTC, offiub commented
Sir the error are much . Do you want to clear it

On Thu, Jun 15, 2023 at 12:11 AM roy hub offi ***@***.***>
wrote:

> Okay sir . You have some issues to rectify
>
> On Thu, Jun 15, 2023 at 12:09 AM Justin Hartman ***@***.***>
> wrote:
>
> > ***@***.**** commented on this pull request.
> > ------------------------------
> >
> > On gpt_engineer/__pycache__/__main__.cpython-310.pyc
> > <
> https://github.com/AntonOsika/gpt-engineer/pull/1#discussion_r1230257190>
> > :
> >
> > You probably want to remove all your pyc files and __pycache__ folder
> > since you're excluding them in the .gitignore file?
> >
> > —
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/AntonOsika/gpt-engineer/pull/1#pullrequestreview-1480431927>,
>
> > or unsubscribe
> > <
> https://github.com/notifications/unsubscribe-auth/BASR7VW2BDQYFVSJZDE7N6DXLJACXANCNFSM6AAAAAAZCATISM>
>
> > .
> > You are receiving this because you are subscribed to this thread.Message
> > ID: ***@***.***>
> >
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/AntonOsika/gpt-engineer/pull/1#issuecomment-1592110166>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BASR7VQUTCTTLZPDVUPLPUTXLJAJZANCNFSM6AAAAAAZCATISM>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2023-06-15 20:17 UTC, patillacode commented
Closing, more context in #38 

Thanks @JacobFV

2023-06-15 20:17 UTC, closed without merging

2023-06-15 20:18 UTC, JacobFV commented
Hi, been busy. Thank you