Remove `delete_existing` option; Introduce archive
AntonOsika/gpt-engineer pull request #409
Opened 2023-06-25 20:47 UTC by azrv

Remove `delete_existing` run option, instead archive memory and workspace on every run;

`archive` is a step since some flows don't generate code and therefore should not archive whatever

Relates to https://github.com/AntonOsika/gpt-engineer/issues/388

2023-06-26 18:20 UTC, AntonOsika commented
Great work!

Added some comments.

Mainly I think we shouldn't let archive be a "step" but we just call it.

Also, feel free to delete the "run_id" functionality.

2023-06-26 18:20 UTC, AntonOsika requested changes

2023-06-26 18:20 UTC, AntonOsika commented on gpt_engineer/db.py
> +    archive: Optional[DB]
Why optional?

```suggestion
    archive: DB
```

2023-06-26 18:20 UTC, AntonOsika commented on gpt_engineer/main.py
> +        # human_review, archive don't need to be dumped
```suggestion
```

2023-06-26 18:20 UTC, AntonOsika commented on gpt_engineer/main.py
> +        # TODO: Don't dump if step returns None
It's OK to write empty files...

```suggestion
```

2023-06-26 18:20 UTC, AntonOsika commented on gpt_engineer/steps.py
> +    if dbs.archive is None:
```suggestion
```

2023-06-26 18:20 UTC, AntonOsika commented on gpt_engineer/steps.py
> +        return
```suggestion
```

2023-06-26 18:20 UTC, AntonOsika commented on gpt_engineer/steps.py
> +        archive,
Let's not make archive a step in this sense, but just call it before we loop over steps!

2023-06-26 18:53 UTC, azrv commented
> Great work!
> 
> Added some comments.
> 
> Mainly I think we shouldn't let archive be a "step" but we just call it.
> 
> Also, feel free to delete the "run_id" functionality.

@AntonOsika 

1) My main concern about archiving NOT being a step is there are "flows" that don't generate code (e.g. EXECUTE_ONLY, EVALUATE) and therefore should not archive things by default. How do we make sure to skip archiving in those cases?
While working on PR I realised archiving functionality complicates code a lot and I'm no sure it provides us any good.
What's inherently wrong with `delete_existing`?

2) Sure! Could you please elaborate on what `run_id` is
I can't seem to find it (not so familiar with the codebase yet) 
`git grep run_id` gives nothing

2023-07-02 13:56 UTC, AntonOsika commented
Merging!

2023-07-02 13:56 UTC, merged

2023-07-02 14:48 UTC, AntonOsika commented
Thanks for the submission @azrv !

Do you want to join discord and DM me there? Happy to chat about future improvements!

2023-07-02 14:49 UTC, AntonOsika commented
Already cleaned up run_id (was callsed run_prefix)