Add Chinese README
AntonOsika/gpt-engineer pull request #427
Opened 2023-06-27 03:12 UTC by PlexPt

2023-06-27 11:33 UTC, AntonOsika commented
Thanks!

How do I know this is the correct translation if I don’t know Chinese? Did you use a tool or translate manually ?

2023-06-29 10:33 UTC, JinchuLi2002 requested changes
The translation looks a bit rough overall, is it machine translated?

2023-06-29 10:33 UTC, JinchuLi2002 commented on README-CN.md
> +中的每个步骤`steps.py`都会将其与 GPT4 的通信历史记录存储在日志文件夹中，并且可以使用`scripts/rerun_edited_message_logs.py`.
This sentence is incomplete

2023-06-29 10:33 UTC, JinchuLi2002 commented on README-CN.md
> +- 填写`prompt`新文件夹中的文件
this makes ppl think 'prompt' is a folder yet in reality it should be a file

2023-07-02 13:50 UTC, AntonOsika commented
I'll close this, will not be able to keep this up to date :/

2023-07-02 13:50 UTC, closed without merging

2023-07-02 13:50 UTC, AntonOsika commented
Thanks for review @JinchuLi2002