Add docker support.
AntonOsika/gpt-engineer pull request #529
Opened 2023-07-13 05:12 UTC by ayoubfletcher

I have created a Dockerfile to build the project into a docker image.

2023-07-15 20:05 UTC, shubham-attri approved these changes

2023-07-16 11:52 UTC, karlderkaefer commented on Dockerfile
> +
bash required when running example 
```
Executing the code...

Note: If it does not work as expected, consider running the code in another way than above.

You can press ctrl+c *once* to stop the execution.

/bin/sh: bash: not found
```

2023-07-16 12:18 UTC, karlderkaefer commented on README.md
> +- `docker run -it --rm -e OPENAI_API_KEY="YOUR OPENAI KEY" -v ./your-project:/project gpt-engineer`
the files that are created from container within volume are written as root user
```
drwxr-xr-x 4 root      root      4096 Jul 16 13:58 workspace
```
this make it's harder to modify, delete or execute files after creating. I would suggest to use this on Linux
```suggestion
- `docker run -it --rm -e OPENAI_API_KEY="YOUR OPENAI KEY" -u $(id -u):$(id -g) -v ./your-project:/project gpt-engineer`
```

2023-07-16 13:15 UTC, karlderkaefer commented on README.md
> +- `docker run -it --rm -e OPENAI_API_KEY="YOUR OPENAI KEY" -v ./your-project:/project gpt-engineer`
and when creating own project the files must be open for any user and group so that root can write
```
chmod a+rw -R my-project
```

2023-07-16 14:53 UTC, AntonOsika requested changes
See proposed comments by @karlderkaefer 👌

2023-07-16 22:57 UTC, closed without merging